php:
  preset: recommended

  enabled:
    - dir_constant
    - ereg_to_preg
    - mb_str_functions
    - no_short_echo_tag
    - strict_comparison
    - phpdoc_link_to_see
    - no_php4_constructor
    - declare_strict_types
    - unalign_double_arrow
    - length_ordered_imports
    - modernize_types_casting
    - return_type_declaration
    - not_operator_with_successor_space

  disabled:
    - align_double_arrow
    - alpha_ordered_imports

  finder:
    not-name:
      - "CountryLoader.php"

js:
  tab-width: 4
  print-width: 120

ts:
  tab-width: 4
  print-width: 120

css:
  tab-width: 4
  print-width: 120
